// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_Rsc91Fa1aOJ8kXSuHJ_SJz2bPSVCMc',
    appId: '1:151184216465:web:4c5b0200f0bf7b6fceca30',
    messagingSenderId: '151184216465',
    projectId: 'restaurant-a0d00',
    authDomain: 'restaurant-a0d00.firebaseapp.com',
    storageBucket: 'restaurant-a0d00.firebasestorage.app',
    measurementId: 'G-5PDZRSHJPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6fKCxvOqTi2mDsXM-mcOQKPpUkFk99hs',
    appId: '1:151184216465:android:a50846df56360b52ceca30',
    messagingSenderId: '151184216465',
    projectId: 'restaurant-a0d00',
    storageBucket: 'restaurant-a0d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3xD-qziWWgNV093qT_5WhTkQPw_ibvVY',
    appId: '1:151184216465:ios:57a363e594044bd8ceca30',
    messagingSenderId: '151184216465',
    projectId: 'restaurant-a0d00',
    storageBucket: 'restaurant-a0d00.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3xD-qziWWgNV093qT_5WhTkQPw_ibvVY',
    appId: '1:151184216465:ios:57a363e594044bd8ceca30',
    messagingSenderId: '151184216465',
    projectId: 'restaurant-a0d00',
    storageBucket: 'restaurant-a0d00.firebasestorage.app',
    iosBundleId: 'com.example.restaurantReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_Rsc91Fa1aOJ8kXSuHJ_SJz2bPSVCMc',
    appId: '1:151184216465:web:cb317c432bc28348ceca30',
    messagingSenderId: '151184216465',
    projectId: 'restaurant-a0d00',
    authDomain: 'restaurant-a0d00.firebaseapp.com',
    storageBucket: 'restaurant-a0d00.firebasestorage.app',
    measurementId: 'G-H35RH33E9P',

  );


}
